export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';


export const SAVE_RECEIPT = 'SAVE_RECEIPT';
export const SAVE_RECEIPT_SUCCESS = 'SAVE_RECEIPT_SUCCESS';
export const SAVE_RECEIPT_ERROR = 'SAVE_RECEIPT_ERROR';
export const LIST_RECEIPTS = 'LIST_RECEIPTS';
export const LIST_RECEIPTS_SUCCESS = 'LIST_RECEIPTS_SUCCESS';
export const LIST_RECEIPTS_ERROR = 'LIST_RECEIPTS_ERROR';